server:
  port: 8087
  servlet:
   context-path: /StockAnalyzer
spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: Stock
      minConnectionsPerHost: 10
      maxConnectionsPerHost: 100
      threadsAllowedToBlockForConnectionMultiplier: 5
      serverSelectionTimeout: 30000
      maxWaitTime: 120000
      maxConnectionIdleTime: 0
      maxConnectionLifeTime: 0
      connectTimeout: 10000
      socketTimeout: 0
      socketKeepAlive: false
      sslEnabled: false
      sslInvalidHostNameAllowed: false
      alwaysUseMBeans: false
      heartbeatSocketTimeout: 20000
      heartbeatConnectTimeout: 20000
      minHeartbeatFrequency: 500
      heartbeatFrequency: 10000
      localThreshold: 15 
      collectionsList :
        - WatchList
        - OAITM
        - SymboolList
constant:
   authenticationUrl: http://localhost:8088/oauth/check_token
   clientId: web-client
   clientScret: web-client-secret
   resourceId: oauth
   urlPattern: /**
   accessPattern: "#oauth2.hasScope('read')"
   baseUrl : http://test1.lisuns.com:4531
   accessKey : 356e6624-cdda-4d8f-af5b-8f95ea19a5e3
   apiName : GetLastQuoteArray
   exchange : NFO
   adminUrlPattern : /admin/**
   userUrlPattern : /user/**
   admin_role : ROLE_ADMIN
   user_role : ROLE_USER
   
   

   
   
logging:
  file: logs/application-debug.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: DEBUG
    com.stokck.oauth2.authserver: DEBUG
    org.hibernate: DEBUG
    
